version: "3.5"
services:
  php-dev_nginx:
    container_name: php-dev_nginx
    image: nginx
    networks:
      - php-dev_network
    ports:
      - ${NGINX_PORT_PUBLIC}:80
      - ${NGINX_PORT_PUBLIC_SSL}:443
    depends_on:
      - php-dev_sql
      # - php-dev_redis
      # - php-dev_p0704
      # - php-dev_p0800
      - main
      - pma
    volumes:
      - ./nginx/configs/sites.conf:/etc/nginx/conf.d/sites.conf
      - ./nginx-logs:/var/log/nginx
      - ./ssl:/etc/letsencrypt
      
  # php-dev_redis:
  #   container_name: php-dev_redis
  #   image: redis:${REDIS_VERSION}
  #   restart: "no"
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   networks:
  #     - php-dev_network
  #   ports:
  #     - ${REDIS_PORT}:6379
  #   volumes:
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf
  #   environment:
  #    - REDIS_REPLICATION_MODE=master

  php-dev_sql:
    container_name: php-dev-mysql
    image: mysql:${MYSQL_VERSION:-latest}
    restart: "no"
    command: --lower_case_table_names=1 --sql_mode="ON" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - php-dev_network
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_PATH}/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_HOST: 0.0.0.0  

  main:
    container_name: main
    networks:
      - php-dev_network
    build:
      context: "./php0801/"
    restart: "no"
    working_dir: /var/www/html
    environment:
      XDEBUG_CONFIG_CLIENT_HOST: ${XDEBUG_CONFIG_CLIENT_HOST}
      XDEBUG_CONFIG_CLIENT_PORT: ${XDEBUG_CONFIG_CLIENT_PORT}
    volumes:
      - ./php0801/apache.conf:/etc/apache2/mods-enabled/apache.conf
      - ./ssl:/etc/letsencrypt      
      - ./www:/var/www/html
    
  pma:
    container_name: pma
    image: phpmyadmin:5.2.0-apache
    networks:
      - php-dev_network
    volumes:
      - ./config.inc.php:/etc/phpmyadmin/config.inc.php
    environment:
      - PMA_ARBITRARY=1
      - MAX_EXECUTION_TIME=18000
      - MEMORY_LIMIT=1024M
      - UPLOAD_LIMIT=1024M

  # php-dev_p0800:
  #   container_name: p0800
  #   networks:
  #     - php-dev_network
  #   build:
  #     context: "./php0800/"
  #   restart: "no"
  #   working_dir: /var/www/html
  #   environment:
  #     XDEBUG_CONFIG_CLIENT_HOST: ${XDEBUG_CONFIG_CLIENT_HOST}
  #     XDEBUG_CONFIG_CLIENT_PORT: ${XDEBUG_CONFIG_CLIENT_PORT}
  #   volumes:
  #     - ./php0800/apache.conf:/etc/apache2/mods-enabled/apache.conf
  #     - ./ssl:/etc/letsencrypt
  #     # - ./www:/var/www/html

  # php-dev_p0704:
  #   container_name: p0704
  #   networks:
  #     - php-dev_network
  #   build:
  #     context: "./php0704/"
  #   restart: "no"
  #   working_dir: /var/www/html
  #   environment:
  #     XDEBUG_CONFIG_CLIENT_HOST: ${XDEBUG_CONFIG_CLIENT_HOST}
  #     XDEBUG_CONFIG_CLIENT_PORT: ${XDEBUG_CONFIG_CLIENT_PORT}
  #   volumes:
  #     - ./php0704/apache.conf:/etc/apache2/mods-enabled/apache.conf
  #     - ./ssl:/etc/letsencrypt
  #     # - ./www:/var/www/html

networks:
  php-dev_network:
    external:
      name: php_dev_network